name: vivu_tet
description: "ViVu Tết – Du xuân Planner Kỷ Tỵ 2026"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0 
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  http: ^1.2.1
  # State management
  provider: ^6.1.2
  cached_network_image: ^3.3.1 
  share_plus: ^10.0.2           
  screenshot: ^3.0.0             
  path_provider: ^2.1.3       
  flutter_launcher_icons: ^0.14.1   

  # Local database
  sqflite: ^2.3.2
  path: ^1.9.0

  # Password hashing
  crypto: ^3.0.3

  # Google Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"   # ← file logo của bạn
  min_sdk_android: 21
  adaptive_icon_background: "#FFF8F0"    # màu nền warmCream cho Android adaptive icon
  adaptive_icon_foreground: "assets/images/logo.jpg"